[project]
name = "flattenbenchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "elasticsearch>=9.2.1",
    "ipython>=9.9.0",
]
